server:
  port: 8888
spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:9005
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/